- build.gradle
- src/main/java/com/aoa/springwebservice/SpringWebserviceApplication.java
- src/main/resources/application.properties
- src/main/resources/static/index.html
- #13 issue
- application.properties, build.gradle 수정
> Add JPA Configuration

- src/main/resources/logback-access.xml
- src/main/resources/logback.xml
- src/test/java/com/aoa/springwebservice/SpringWebserviceApplicationTests.java
- src/test/java/com/aoa/springwebservice/test/JPATestDomain.java
- src/test/java/com/aoa/springwebservice/test/JPATestDomainRepository.java
- add logback xml
- jpa test & log
> Add Logback

- src/main/java/com/aoa/springwebservice/exception/FileStorageException.java
- src/main/java/com/aoa/springwebservice/property/FileStorageProperties.java
- src/main/java/com/aoa/springwebservice/service/FileStorageService.java
- src/main/java/com/aoa/springwebservice/web/ApiMenuController.java
- src/main/resources/application.properties
- src/main/resources/static/index.html
- File Controller, Service, Properties 추가 및 설정
> Add FileStorage Logic

- src/main/java/com/aoa/springwebservice/exception/FileStorageException.java
- src/main/java/com/aoa/springwebservice/property/FileStorageProperties.java
- src/main/java/com/aoa/springwebservice/service/FileStorageService.java
- src/main/java/com/aoa/springwebservice/web/ApiMenuController.java
- src/main/resources/application.properties
- src/main/resources/static/index.html
> Feature add menu

- src/main/java/com/aoa/springwebservice/dto/InputStoreDTO.java
- src/main/java/com/aoa/springwebservice/web/ApiStoreController.java
- src/main/resources/static/js/common.js
- src/main/resources/static/js/test.js
- src/main/resources/templates/test.html
Feature store #16 
- HTML, CSS 수정
- File input 처리를 위한 Async 요청 수정
- InputDTO 수정 (phoneNumber) 
- 가게 등록 성공시 임시로 페이지 이동
+ Daum API 관련 버그 픽스 및 요청 실패시 처리 루틴 필요
> Feature store #16 프론트 HTML, CSS, JS 수정 

- src/main/java/com/aoa/springwebservice/WebMvcConfig.java
- src/main/java/com/aoa/springwebservice/domain/Menu.java
- src/main/java/com/aoa/springwebservice/domain/Store.java
- src/main/java/com/aoa/springwebservice/domain/support/MenuDTO.java
- src/main/java/com/aoa/springwebservice/service/MenuService.java
- src/main/java/com/aoa/springwebservice/web/ApiMenuController.java
- src/main/java/com/aoa/springwebservice/web/PageController.java
- src/main/resources/import.sql
- src/main/resources/templates/registMenu.html
- src/test/java/com/aoa/springwebservice/domain/MenuTest.java
- src/test/java/com/aoa/springwebservice/domain/StoreTest.java
1. 에러 로직 처리 추가 필요
1. 세션에서 User / Store (로그인정보)받고,
store 없는 경우 등록하는 페이지로 보내거나 가게 등록하라는 알림 주도록 추가
> [Feature/add menu/#42]

- src/main/java/com/aoa/springwebservice/WebMvcConfig.java
- src/main/java/com/aoa/springwebservice/domain/MenuRepository.java
- src/main/java/com/aoa/springwebservice/domain/support/MenuOutputDTO.java
- src/main/java/com/aoa/springwebservice/service/FileStorageService.java
- src/main/java/com/aoa/springwebservice/service/MenuService.java
- src/main/java/com/aoa/springwebservice/web/ApiMenuController.java
- src/main/resources/static/css/owner.css
- src/main/resources/static/js/common.js
- src/main/resources/static/js/menu.js
- src/main/resources/templates/displayMenu.html
- src/main/resources/templates/registMenu.html
- MenuRepository에 findAllByStore 생성
- MenuOutputDTO 새로 생성
- File StrorageService에서 baseUrl append로 계속 길어지는 버그 수정
- MenuService에 storeId로 메뉴리스트 반환하는 메소드 추가 
- 프론트에서 페이지최초로딩시 Ajax통신으로 메뉴데이터 받아옴
- Ajax 통신진행중 프리로더 추가
> Add 메뉴조회 BE 및 FE ajax 작업 #53

- src/main/java/com/aoa/springwebservice/exception/DefaultControllerAdvice.java
- src/main/java/com/aoa/springwebservice/exception/DefaultRestControllerAdvice.java
- 불필요 코드 제거
- responseEntity -> ValidationErrorResponse
> [Fix] validation Error /#59

- src/main/java/com/aoa/springwebservice/domain/Order.java
- src/main/java/com/aoa/springwebservice/domain/OrderItem.java
- src/main/java/com/aoa/springwebservice/dto/OrderFormDTO.java
- src/main/java/com/aoa/springwebservice/dto/OrderItemDTO.java
- Order, OrderItem 도메인생성
- OrderFormDTO, OrderItemDTO생성
> Add order domain and DTO #74

- src/main/java/com/aoa/springwebservice/WebMvcConfig.java
- src/main/java/com/aoa/springwebservice/domain/MaxCount.java
- src/main/java/com/aoa/springwebservice/domain/Menu.java
- src/main/java/com/aoa/springwebservice/domain/Reservation.java
- src/main/java/com/aoa/springwebservice/domain/ReservationRepository.java
- src/main/java/com/aoa/springwebservice/domain/Store.java
- src/main/java/com/aoa/springwebservice/domain/StoreRepository.java
- src/main/java/com/aoa/springwebservice/service/ReservationService.java
- src/main/java/com/aoa/springwebservice/service/StoreService.java
- src/main/java/com/aoa/springwebservice/service/support/CurrentReservationSelector.java
- src/main/java/com/aoa/springwebservice/service/support/LastReservationSelector.java
- src/main/java/com/aoa/springwebservice/service/support/ReservationSelector.java
- src/main/java/com/aoa/springwebservice/web/ApiMenuController.java
- src/main/java/com/aoa/springwebservice/web/PageController.java
- src/main/resources/templates/displayReservation.html
- src/test/java/com/aoa/springwebservice/Service/ReservationServiceTest.java
- src/test/java/com/aoa/springwebservice/SpringWebserviceApplicationTests.java
- src/test/java/com/aoa/springwebservice/domain/repository/ReservationRepositoryTest.java
> Feature/get reservations/#78

- src/main/resources/templates/registMenu.html
- src/main/resources/templates/registStore.html
- 메뉴등록시 텍스트 검증 추가 
- 파일크기제한 추가(메뉴등록, 가게등록)
> Add Menu Input Valid, File Valid

- src/main/java/com/aoa/springwebservice/RestResponse.java
- src/main/java/com/aoa/springwebservice/domain/Store.java
- src/main/java/com/aoa/springwebservice/dto/OrderFormDTO.java
- src/main/java/com/aoa/springwebservice/dto/StoreOutputDTO.java
- src/main/java/com/aoa/springwebservice/service/MenuService.java
- src/main/java/com/aoa/springwebservice/service/StoreService.java
- src/main/java/com/aoa/springwebservice/web/ApiMenuController.java
- src/main/java/com/aoa/springwebservice/web/ApiOrderController.java
- src/main/java/com/aoa/springwebservice/web/PageController.java
- src/main/resources/static/js/client_order.js
- src/main/resources/templates/createOrder.html
- src/main/resources/templates/openReservation.html
- src/main/resources/templates/showOrderResult.html
- src/test/java/com/aoa/springwebservice/support/DateTest.java
- 구매자 주문 플로우 중 결제 완료 페이지 제외 
- 결제 완료 페이지 리다이렉트 관련 버그 픽스 필요함
> Feature/refactor order controller/#94

- src/main/java/com/aoa/springwebservice/WebMvcConfig.java
- src/main/java/com/aoa/springwebservice/domain/Store.java
- src/main/java/com/aoa/springwebservice/web/ApiMenuController.java
- src/main/java/com/aoa/springwebservice/web/ApiReservationController.java
- src/main/resources/import.sql
- src/main/resources/static/js/menu.js
- src/main/resources/static/js/owner_reservation.js
- src/main/resources/templates/menulist.html
- src/main/resources/templates/openReservation.html
* Fix openReservation-related Nullpointer Exception and Path
* Fix already registed store
- 이미 등록된 가게를 다시 등록시도시 다른페이지 띄워줌
* Fix Not Working openReservation html
- API변경 및 기타 버그 (중복 class명에 등록된 이벤트 핸들러 등.... ) 픽스
- 메뉴 삭제 추가 버그 픽스
- 성공시 Redirect
> Fix openReservation #105 (PR #107)

- src/main/java/com/aoa/springwebservice/WebMvcConfig.java
- src/main/java/com/aoa/springwebservice/domain/Store.java
- src/main/java/com/aoa/springwebservice/web/ApiMenuController.java
- src/main/java/com/aoa/springwebservice/web/ApiReservationController.java
- src/main/resources/import.sql
- src/main/resources/static/js/materialize.js
- src/main/resources/static/js/menu.js
- src/main/resources/static/js/override.js
- src/main/resources/static/js/owner_reservation.js
- src/main/resources/templates/menulist.html
- src/main/resources/templates/openReservation.html
- src/main/resources/templates/registMenu.html
- FE ) 기존 materialize.js 에서 변경한 form validation 내용 CustomInputValidator 클래스로 분리
- 기존 validate 클래스 대신 custom-validate 이용
- CustomInputValidator  module을  import하여 사용
> Feature/refactor form validation/#110

- .gitignore
- src/main/java/com/aoa/springwebservice/WebMvcConfig.java
- src/main/java/com/aoa/springwebservice/web/PageController.java
- src/main/resources/import.sql
- src/main/resources/templates/alreadyRegisted.html
- src/main/resources/templates/displayMenu.html
- src/main/resources/templates/displayReservation.html
- src/main/resources/templates/fail.html
- src/main/resources/templates/header.html
- src/main/resources/templates/openReservation.html
- src/main/resources/templates/registMenu.html
- src/main/resources/templates/registStore.html
- src/main/resources/templates/signin.html
- Change delete daum postcode from registMenu
- Change gitignore file for import.sql
- Change File name form
- Change block regist menus from unregisted store 
- Change site title
- Change nav title
- Change import.sql
> Change Owner pages Errors

- src/main/resources/static/css/clientCommon.css
- src/main/resources/static/css/commonReal.css
- src/main/resources/static/js/client_order.js
- src/main/resources/static/js/ctrl.js
- src/main/resources/static/js/owner_reservation.js
- src/main/resources/static/js/storeinfo.js
- src/main/resources/templates/clientFooter.html
- src/main/resources/templates/createOrder.html
- src/main/resources/templates/openReservation.html
-  주문 완료
-- 카드에서 가게 정보 css(미현)
- 예약 등록
-- 프론트 체크 -- 최대 수량 < 인당 최대 예약 체크
-- ctrl (수량조절) js 개선
-- 예약 등록시, 메뉴 하나도 선택 안했을 경우 에러 메세지 출력 및 예약 등록 불가 (F/E)
> Fix front-related bugs #144 (PR #138)

- src/main/java/com/aoa/springwebservice/RestResponse.java
- src/main/java/com/aoa/springwebservice/WebMvcConfig.java
- src/main/java/com/aoa/springwebservice/domain/Store.java
- src/main/java/com/aoa/springwebservice/dto/ReservationFormDTO.java
- src/main/java/com/aoa/springwebservice/exception/DefaultControllerAdvice.java
- src/main/java/com/aoa/springwebservice/exception/DefaultRestControllerAdvice.java
- src/main/java/com/aoa/springwebservice/security/AuthorizedStore.java
- src/main/java/com/aoa/springwebservice/security/StoreHandlerMethodArgumentResolver.java
- src/main/java/com/aoa/springwebservice/service/MenuService.java
- src/main/java/com/aoa/springwebservice/web/ApiMenuController.java
- src/main/java/com/aoa/springwebservice/web/ApiStoreController.java
- src/main/resources/static/js/client_order.js
- src/main/resources/static/js/kakao_login.js
- src/main/resources/static/js/kakao_logout.js
- src/main/resources/static/js/owner_reservation.js
- src/test/java/com/aoa/springwebservice/security/AuthorizedStoreTest.java
- src/test/java/com/aoa/springwebservice/service/OrderServiceTest.java
- src/test/java/com/aoa/springwebservice/service/ReservationServiceTest.java
- @AuthorizedStore : 세션 로그인 유저가 해당 store에 권한 있는지 여부 확인
- 테스트 코드 작성 (변경 가능성 있음)
- 버그 픽스 -- RestControllerAdvice 우선순위 > ControllerAdvice 우선순위
- 기존 ApiReservationController 의 createReservation 메소드 임의 변경 - AuthorizedStore 적용
- RestResponse 변경 -- @JsonUnwrapped 적용, ApiError Response용 팩토리 메서드 추가
- 이에 따른 프론트 변경 (result.data.url -> result.url)
> Add Exception Handler for Rest (AuthorizedStore)

- src/main/java/com/aoa/springwebservice/domain/Menu.java
- src/main/java/com/aoa/springwebservice/domain/Order.java
- src/main/java/com/aoa/springwebservice/dto/MenuDTOToUpload.java
- src/main/java/com/aoa/springwebservice/exception/DefaultRestControllerAdvice.java
- src/main/java/com/aoa/springwebservice/security/AuthorizedStore.java
- src/main/java/com/aoa/springwebservice/security/StoreHandlerMethodArgumentResolver.java
- src/main/java/com/aoa/springwebservice/service/MenuService.java
- src/main/java/com/aoa/springwebservice/service/OrderService.java
- src/main/java/com/aoa/springwebservice/service/ReservationService.java
- src/main/java/com/aoa/springwebservice/web/ApiMenuController.java
- src/main/java/com/aoa/springwebservice/web/ApiOrderController.java
- src/main/java/com/aoa/springwebservice/web/ApiReservationController.java
- src/main/java/com/aoa/springwebservice/web/PageController.java
- src/main/resources/static/js/client_order.js
- src/main/resources/static/js/ctrl.js
- src/main/resources/static/js/owner_reservation.js
- src/main/resources/templates/openReservation.html
- src/main/resources/templates/showOrders.html
- src/test/java/com/aoa/springwebservice/domain/MenuTest.java
- src/test/java/com/aoa/springwebservice/security/AuthorizedStoreTest.java
- src/test/java/com/aoa/springwebservice/service/ReservationServiceTest.java
-AuthoStore resolver  -- Owner &  Store check and isOpen 
- 기타 버그 픽스 (ctrl, css..)
> Refactor checking precondition exception fix/#149

- src/main/java/com/aoa/springwebservice/domain/Store.java
- src/main/java/com/aoa/springwebservice/dto/StoreOutputDTO.java
- src/main/java/com/aoa/springwebservice/dto/StoreUpdateInputDTO.java
- src/main/java/com/aoa/springwebservice/service/StoreService.java
- src/main/java/com/aoa/springwebservice/web/ApiStoreController.java
- src/main/java/com/aoa/springwebservice/web/PageController.java
- src/main/resources/application.yml
- src/main/resources/static/css/info.css
- src/main/resources/static/js/storeinfo.js
- src/main/resources/templates/header.html
- src/main/resources/templates/updateStore.html
- src/test/java/com/aoa/springwebservice/domain/StoreTest.java
- src/test/java/com/aoa/springwebservice/security/AuthorizedStoreTest.java
* Add store information modal
* Add connect event modal and button
- 구매자 페이지 모달과 버튼 이벤트연결
* Change Address module, address & image valid module
- 주소선택시 창 닫히게 설정
- 주소, 이미지경로에 정상적인 밸리데이션 적용
* Change section class in storeInfo
* Add updateStore - not done
* Add store information update #155
- update store information
- modal 이미지 비율변경 추가
> Add store information update #155 (PR #156)

- src/main/java/com/aoa/springwebservice/exception/DefaultRestControllerAdvice.java
- src/main/java/com/aoa/springwebservice/web/ApiMenuController.java
- src/main/java/com/aoa/springwebservice/web/ApiReservationController.java
- src/main/java/com/aoa/springwebservice/web/ApiStoreController.java
- src/main/java/com/aoa/springwebservice/web/PageController.java
- src/main/resources/import.sql
- src/main/resources/templates/alreadyRegisted.html
- src/main/resources/templates/header.html
- src/main/resources/templates/registStore.html
- src/main/resources/templates/signin.html
- src/main/resources/templates/updateStore.html
6. 헤더 홈버튼 URL 제대로 주기  -> 제거 [@준호]
9. helper 안에 영어, 스페이스바 입력 안되는 거 작성(wrong 대신)  [@준호]
10. 판매자 URL 복사 안되는 것 [ @준호]
5. 페이지 흐름 조절(모든 등록은 수정이나 조회 페이지로 이동하게(가게, 메뉴, 예약)) - result/success 페이지 변경  [@준호]
> Fix/ui flow/#163

- src/main/java/com/aoa/springwebservice/exception/CustomerOrderException.java
- src/main/java/com/aoa/springwebservice/exception/DefaultControllerAdvice.java
- src/main/java/com/aoa/springwebservice/service/StoreService.java
- src/main/java/com/aoa/springwebservice/web/PageController.java
- src/main/resources/templates/customerError.html
- Add CustomerOrderException
- Change exception handler
- Add customer error pages
> Refactor Customer Error Page #184

- src/main/java/com/aoa/springwebservice/exception/DefaultControllerAdvice.java
- src/main/resources/static/css/common.css
- src/main/resources/static/css/error.css
- src/main/resources/static/css/override.css
- src/main/resources/templates/fail.html
- src/main/resources/templates/header.html
- Refactor Owner error page CSS
- Refactor side nav CSS
> Refactor Owner error page & Side nav
